### ISSUE TITLE
`No internet connection` popup

### ISSUE THREAD

**Issue by LenartBucar** [beziapp/beziapp.github.io#5]
Upon visiting the page [gradings](https://beziapp.github.io/pages/gradings.html) a popup `No internet connection!` is displayed, despite obviously having internet connection. This is the only page this popup appears on. 

Issue replicated on:
- Desktop, Vivaldi 2.10.1745.27 (chromium-based)
- Desktop, Mozilla Firefox 60.5.0esr
- Desktop, Google Chrome 79.0.3945.130 (Official Build)
- Mobile, Google Chrome 79.0.3945.136

**Comment by rstular** [comment]
Hm, that's strange, I'm not able to reproduce the issue on chromium 79.0.3945.130 nor on Firefox 68.4.1esr... Are you using Windows?
Also, a couple of troubleshooting steps:
Does the issue persist after signing out and back in?
If so, does forcing a refresh (with the in-app button) help?

Oh and by the way, I'd really appreciate it if you could send any Javascript console errors. 

Thank you for your report and best regards, 
rstular

**Comment by LenartBucar** [comment]
I am using Windows 10 version 1809 build 17763.973 with ethernet connection as Desktop and Oxygen OS 10.0.3 with wi-fi connection as Mobile. 
Neither signing out and signing back in nor forcing a refresh using an in-app button fixes the issue; the popup persists. 

Javascript console does not produce any errors, however, there are 8 identical `verbose messages`:
```
[Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
```

**Comment by sijanec** [comment]
Seeing the nginx uptime on the app server, no downtime was reported and service was continuously running for 45 days at the time of writing. No network bottlenecks or extensive usage was detected on the server.

Does the issue persist?

**Comment by LenartBucar** [comment]
That is correct, the issue is still present, even after retrying both of the troubleshooting steps mentioned above.

**Comment by rstular** [comment]
A fix was implemented in 1.0.5, does updating the app now resolve it?

**Comment by LenartBucar** [comment]
No, even after updating the app and retrying both steps, the issue still persists.

**Comment by rstular** [comment]
The issue may be caused by a typo (missing semicolon), though I doubt it, because it would be showing in the console log. Please update to 1.0.6-beta and try again.

The popup you are seeing is only shown when the jQuery AJAX request fails ([code that triggers it is here](https://github.com/beziapp/beziapp.github.io/blob/master/js/gradings.js#L128), but you said that requests on other pages succeed without any issues, which is the part that confuses me the most.
The typo is the only difference I was able to find between the two ajax code blocks, so hopefully this fixes it.
